/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpooitalo;

import javax.swing.JOptionPane;


/**
 *
 * @author ipvve
 */
//Nome: Italo Pereira Ventura -  RA: 2467259

public class CadNad extends javax.swing.JFrame {

    private Nadador n;
    private final BancoNadador banco = new BancoNadador();

    private static CadNad unicoCadNad;

    /**
     * Creates new form cadPes
     */
    private CadNad() {
        initComponents();
    }

    public static CadNad getCadNad() {
        if (unicoCadNad == null) {
            unicoCadNad = new CadNad();
        }
        return unicoCadNad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxRua = new javax.swing.JTextField();
        cxIdatleta = new javax.swing.JTextField();
        cxNumCasa = new javax.swing.JTextField();
        rotTelresponsavel = new javax.swing.JLabel();
        rotAltura = new javax.swing.JLabel();
        rotCategoria = new javax.swing.JLabel();
        cxTelresponsavel = new javax.swing.JTextField();
        cxMetros = new javax.swing.JTextField();
        cxEstilo = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btConsAtleCor = new javax.swing.JButton();
        BtBanco = new javax.swing.JToggleButton();
        rotAno = new javax.swing.JLabel();
        cxAno = new javax.swing.JTextField();
        rotRg = new javax.swing.JLabel();
        rotRua = new javax.swing.JLabel();
        rotNumCasa = new javax.swing.JLabel();
        rotNome = new javax.swing.JLabel();
        rotSobrenome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxSobrenome = new javax.swing.JTextField();
        btInsPas = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rotIdatleta = new javax.swing.JLabel();
        cxRg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Nadador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        rotTelresponsavel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotTelresponsavel.setText("TELEFONE RESPONSAVEL");

        rotAltura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotAltura.setText("METROS");

        rotCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotCategoria.setText("ESTILO");

        btExcluir.setText("Exclui pelo RG");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar por RG");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsAtleCor.setText("Consultar por RG");
        btConsAtleCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsAtleCorActionPerformed(evt);
            }
        });

        BtBanco.setText("Banco de Dados");
        BtBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBancoActionPerformed(evt);
            }
        });

        rotAno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotAno.setText("ANO QUE NASCEU");

        cxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAnoActionPerformed(evt);
            }
        });

        rotRg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotRg.setText("RG");

        rotRua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotRua.setText("RUA");

        rotNumCasa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNumCasa.setText("NUMERO CASA");

        rotNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotNome.setText("NOME");

        rotSobrenome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotSobrenome.setText("SOBRENOME");

        btInsPas.setText("Inserir");
        btInsPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsPasActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rotIdatleta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotIdatleta.setText("ID ATLETA");

        jButton1.setText("Relatorio de Atletas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("É esperado só letras");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("É esperado só letras");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("É esperado 4 digitos");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("É esperado 7 digitos");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("É esperado entre 1 a 5 digitos");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("É esperado só letras");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("É esperado 8 digitos do ID");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel8.setText("É esperado só letras");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel9.setText("É esperado 11 digitos");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel10.setText("É esperado 1 a 3 digitos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btInsPas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btConsAtleCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxEstilo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxMetros))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotTelresponsavel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxTelresponsavel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotIdatleta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxIdatleta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotNumCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNumCasa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRua))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotRg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRg))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxAno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotSobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxSobrenome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rotNome))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotSobrenome)
                    .addComponent(cxSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotAno)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotRg)
                    .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotRua)
                    .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNumCasa)
                    .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotIdatleta)
                    .addComponent(cxIdatleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotTelresponsavel)
                    .addComponent(cxTelresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotAltura)
                    .addComponent(cxMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotCategoria)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cxEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsPas)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtBanco)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btConsAtleCor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        delNadRg();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sai();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        altNadRg();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsAtleCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsAtleCorActionPerformed
        consNadRg();
    }//GEN-LAST:event_btConsAtleCorActionPerformed

    private void BtBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBancoActionPerformed
        ImpreBanco();
    }//GEN-LAST:event_BtBancoActionPerformed

    private void btInsPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsPasActionPerformed
        insNad();
        limpar();
    }//GEN-LAST:event_btInsPasActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abreRelNadador();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAnoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    public void abreRelNadador(){
        RelNadador.getRelNadador(banco).setVisible(true);
    }
    
     
    public void consNadRg() {
        n = new Nadador();
        String RgText = cxRg.getText().trim(); 

        if (RgText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O RG não pode estar em branco!", "ERRO de RG", JOptionPane.ERROR_MESSAGE);
            cxRg.requestFocus();
            return;
        }

        if (!RgText.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O RG deve conter apenas números!", "ERRO de RG", JOptionPane.ERROR_MESSAGE);
            cxRg.requestFocus();
            return;
        }

        try {
            n.setRg(Integer.parseInt(cxRg.getText()));
            n = banco.consNadRg(n);

            if (n != null) {
                cxNome.setText(n.getNome());
                cxSobrenome.setText(n.getSobrenome());
                cxAno.setText(Integer.toString(n.getIdade()));
                cxRg.setText(Integer.toString(n.getRg()));
                cxRua.setText(n.getD1().getRua());
                cxIdatleta.setText(Integer.toString(n.getD1().getIdatleta()));
                cxNumCasa.setText(Integer.toString(n.getD1().getNumcasa()));
                cxTelresponsavel.setText(Long.toString(n.getD1().getTelresponsavel()));
                cxMetros.setText(Integer.toString(n.getMetros()));
                cxEstilo.setText(n.getEstilo());
                JOptionPane.showMessageDialog(null, "Confirme os dados do Atleta", "Confirmação de Dados", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Não existe Atleta com esse RG", "Atleta inexistente", JOptionPane.WARNING_MESSAGE);
                limpar();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O Rg deve ser um número inteiro!", "ERRO de RG", JOptionPane.ERROR_MESSAGE);
            cxNome.requestFocus();
        }
    }

    
    public void altNadRg() {
        n = new Nadador();
        try {
            n.setRg(Integer.parseInt(cxRg.getText()));

            n = banco.altNadRg(n);

            if (n != null) {
                cxNome.setText(n.getNome());
                cxSobrenome.setText(n.getSobrenome());
                cxAno.setText(Integer.toString(n.CalculoIdade()));
                cxRg.setText(Integer.toString(n.getRg()));
                cxRua.setText(n.getD1().getRua());
                cxNumCasa.setText(Integer.toString(n.getD1().getNumcasa()));
                cxIdatleta.setText(Integer.toString(n.getD1().getIdatleta()));
                cxTelresponsavel.setText(String.valueOf(n.getD1().getTelresponsavel()));
                cxMetros.setText(Integer.toString(n.getMetros()));
                cxEstilo.setText(n.getEstilo());
                JOptionPane.showMessageDialog(null, "Confirme os dados do Atleta atualizados com sucesso", "Atualização do Atleta", 1);
                limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Não existe Atleta com esse RG", "RG inexistente", 0);
                limpar();
            }
        } //fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O RG deve ser um número inteiro!", "ERRO de RG", 0);
            cxNome.setText("");
            cxNome.requestFocus();
        }
    }
    
    public void delNadRg() {
        n = new Nadador();
        try {
            n.setRg(Integer.parseInt(cxRg.getText()));

            n = banco.consNadRg(n);

            if (n != null) {
                cxNome.setText(n.getNome());
                cxSobrenome.setText(n.getSobrenome());
                cxAno.setText(Integer.toString(n.CalculoIdade()));
                cxRg.setText(Integer.toString(n.getRg()));
                cxRua.setText(n.getD1().getRua());
                cxNumCasa.setText(Integer.toString(n.getD1().getNumcasa()));
                cxIdatleta.setText(Integer.toString(n.getD1().getIdatleta()));
                cxTelresponsavel.setText(String.valueOf(n.getD1().getTelresponsavel()));
                cxMetros.setText(Integer.toString(n.getMetros()));
                cxEstilo.setText(n.getEstilo());
                cxNome.requestFocus();

                int x = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse Atleta?", "Confirmação de exclusão", JOptionPane.YES_NO_CANCEL_OPTION);
                if (x == 0) {
                    banco.delNadRg(n);
                    JOptionPane.showMessageDialog(null, "Atleta excluído com sucesso", "Exclusão de Atleta", 1);
                    limpar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não existe Atleta com esse RG", "RG inexistente", 0);
                limpar();
            }
        } //fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O RG deve ser um número inteiro!", "ERRO de RG", 0);
            cxNome.setText("");
            cxNome.requestFocus();
        }
    }
    
    public void insNad() {
        n = new Nadador();
        try {
            
            n.setNome(validarString(cxNome.getText()));
            n.setSobrenome(validarString(cxSobrenome.getText()));
            n.setIdade(validarIdade(cxAno.getText()));
            n.setRg(validarRg(cxRg.getText()));
            n.getD1().setRua(validarString(cxRua.getText()));
            n.getD1().setNumcasa(validarNumCasa(cxNumCasa.getText()));
            n.getD1().setIdatleta(validarIdatleta(cxIdatleta.getText()));
            n.getD1().setTelresponsavel(validarTelResponsavel(cxTelresponsavel.getText()));
            n.setMetros(Integer.parseInt(cxMetros.getText()));
            n.setEstilo(validarString(cxEstilo.getText()));
            
            n = banco.cadNad(n);

            if (n != null) {
                JOptionPane.showMessageDialog(null, "Atleta cadastrado com sucesso!", "Cadastro OK", 1);
                limpar();
            } else {
                JOptionPane.showMessageDialog(null, "Já existe atleta com esse RG!", "ERRO de Cadastro", 0);
                cxNome.setText("");
                cxNome.requestFocus();
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O Rg deve ser um número inteiro!", "ERRO de RG", 0);
            cxNome.setText("");
            cxNome.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }
    
    private String validarString(String input) throws Exception {
        if (input.matches(".*\\d.*")) {
            throw new Exception("A entrada não pode conter números!");
        }
        return input;
    }
    private int validarIdade(String input) throws Exception {
        if (input.length() != 4) {
            throw new Exception("A Idade deve conter exatamente 4 dígitos numéricos!");
        }

        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            throw new Exception("A Idade deve ser um número inteiro!");
        }
    }

    private int validarRg(String input) throws Exception {
        if (input.length() != 7) {
            throw new Exception("O RG deve conter exatamente 7 dígitos numéricos!");
        }

        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            throw new Exception("O RG deve ser um número inteiro!");
        }
    }

    private int validarNumCasa(String input) throws Exception {
        try {
            int num = Integer.parseInt(input);
            if (num < 1 || num > 999999) {
                throw new Exception("O Número da Casa deve estar entre 1 e 999999!");
            }
            return num;
        } catch (NumberFormatException e) {
            throw new Exception("O Número da Casa deve ser um número inteiro!");
        }
    }

    private int validarIdatleta(String input) throws Exception {
        if (input.length() != 8) {
            throw new Exception("O Id do Atleta deve conter exatamente 8 dígitos numéricos!");
        }

        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            throw new Exception("O Id do Atleta deve ser um número inteiro!");
        }
    }

    private long validarTelResponsavel(String input) throws Exception {
        if (input.length() != 11) {
            throw new Exception("O Telefone do Responsável deve conter exatamente 11 dígitos numéricos!");
        }

        try {
            return Long.parseLong(input);
        } catch (NumberFormatException e) {
            throw new Exception("O Telefone do Responsável deve ser um número válido!");
        }
    }
    
private int validarAltura(String input) throws Exception {
    try {
        int altura = Integer.parseInt(input);
        if (altura < 1 || altura > 999) {
            throw new Exception("A Altura deve estar entre 1 e 999!");
        }
        return altura;
    } catch (NumberFormatException e) {
        throw new Exception("A Altura deve ser um número inteiro válido!");
    }
}

   
    public void limpar() {
        cxNome.setText("");
        cxSobrenome.setText("");
        cxAno.setText("");
        cxRg.setText("");
        cxRua.setText("");
        cxIdatleta.setText("");
        cxNumCasa.setText("");
        cxTelresponsavel.setText("");
        cxMetros.setText("");
        cxEstilo.setText("");
        cxNome.requestFocus();
    }

    public void ImpreBanco() {

        n = banco.ImpreBanco(n);

    }

    public void sai() {
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == 0) {
            //System.exit(0);
            dispose();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtBanco;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsAtleCor;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInsPas;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAno;
    private javax.swing.JTextField cxEstilo;
    private javax.swing.JTextField cxIdatleta;
    private javax.swing.JTextField cxMetros;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumCasa;
    private javax.swing.JTextField cxRg;
    private javax.swing.JTextField cxRua;
    private javax.swing.JTextField cxSobrenome;
    private javax.swing.JTextField cxTelresponsavel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel rotAltura;
    private javax.swing.JLabel rotAno;
    private javax.swing.JLabel rotCategoria;
    private javax.swing.JLabel rotIdatleta;
    private javax.swing.JLabel rotNome;
    private javax.swing.JLabel rotNumCasa;
    private javax.swing.JLabel rotRg;
    private javax.swing.JLabel rotRua;
    private javax.swing.JLabel rotSobrenome;
    private javax.swing.JLabel rotTelresponsavel;
    // End of variables declaration//GEN-END:variables
}
