/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpooitalo;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ipvve
 */
//Nome: Italo Pereira Ventura -  RA: 2467259
public class RelCorredor extends javax.swing.JFrame {
    

    public static RelCorredor unicoRelCorredor;
    public static BancoCorredor banco;
 
    
    public static RelCorredor getRelCorredor(BancoCorredor banco1){
        
        banco = banco1;
        
        if(unicoRelCorredor == null){
            unicoRelCorredor = new RelCorredor();
        }
        return unicoRelCorredor;
    }
    /**
     * Creates new form RelCarga
     */
    private RelCorredor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco de Atletas - Corredor");
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "IDADE", "RG", "NOME DA RUA", "NUM CASA", "ID ATLETA", "TEL RESPONSAVEL", "DISTANCIA", "MODALIDADE"
            }
        ));
        tblCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCorMouseClicked
        selecTabCor();
    }//GEN-LAST:event_tblCorMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       listaTab();
    }//GEN-LAST:event_formPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
        listaTab();
    }//GEN-LAST:event_formWindowActivated

    public void selecTabCor(){
        String valLinTab = "";
        int posLin = tblCor.getSelectedRow();
        
        for(int coluna = 0;coluna < tblCor.getColumnCount(); coluna++){
            valLinTab += tblCor.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna+1 <tblCor.getRowCount()){
                valLinTab +=" - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
     public void listaTab() {
        DefaultTableModel modelo = (DefaultTableModel) tblCor.getModel();
        int posLin = 0;

        modelo.setRowCount(posLin);

        for (Corredor cor : banco.getBdCor()) {
            modelo.insertRow(posLin, new Object[]{cor.getNome(), cor.getSobrenome(), cor.CalculoIdade(), cor.getRg(), cor.getD1().getRua(), cor.getD1().getNumcasa(), cor.getD1().getIdatleta(), cor.getD1().getTelresponsavel(),cor.getDistancia(),cor.getModalidade()});                         
            posLin++;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCor;
    // End of variables declaration//GEN-END:variables
}
