/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpooitalo;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ipvve
 */
//Nome: Italo Pereira Ventura -  RA: 2467259
public class RelNadador extends javax.swing.JFrame {
    

    public static RelNadador unicoRelNadador;
    public static BancoNadador banco;
 
    
    public static RelNadador getRelNadador(BancoNadador banco1){
        
        banco = banco1;
        
        if(unicoRelNadador == null){
            unicoRelNadador = new RelNadador();
        }
        return unicoRelNadador;
    }
    /**
     * Creates new form RelCarga
     */
    private RelNadador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco de Atletas - Nadador");
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblNad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "IDADE", "RG", "NOME DA RUA", "NUM CASA", "ID ATLETA", "TEL RESPONSAVEL", "METROS", "ESTILO"
            }
        ));
        tblNad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNadMouseClicked
        selecTabNad();
    }//GEN-LAST:event_tblNadMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       listaTab();
    }//GEN-LAST:event_formPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
        listaTab();
    }//GEN-LAST:event_formWindowActivated
    
    public void selecTabNad(){
        String valLinTab = "";
        int posLin = tblNad.getSelectedRow();
        
        for(int coluna = 0;coluna < tblNad.getColumnCount(); coluna++){
            valLinTab += tblNad.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna+1 <tblNad.getRowCount()){
                valLinTab +=" - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
     public void listaTab() {
        DefaultTableModel modelo = (DefaultTableModel) tblNad.getModel();
        int posLin = 0;

        modelo.setRowCount(posLin);

        for (Nadador nad : banco.getBdNad()) {
            modelo.insertRow(posLin, new Object[]{nad.getNome(), nad.getSobrenome(), nad.CalculoIdade(), nad.getRg(), nad.getD1().getRua(), nad.getD1().getNumcasa(), nad.getD1().getIdatleta(), nad.getD1().getTelresponsavel(),nad.getMetros(),nad.getEstilo()});                         
            posLin++;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNad;
    // End of variables declaration//GEN-END:variables
}
