/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpooitalo;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ipvve
 */
//Nome: Italo Pereira Ventura -  RA: 2467259

public class RelSaltador extends javax.swing.JFrame {
    

    public static RelSaltador unicoRelSaltador;
    public static BancoSaltador banco;
 
    
    public static RelSaltador getRelSaltador(BancoSaltador banco1){
        
        banco = banco1;
        
        if(unicoRelSaltador == null){
            unicoRelSaltador = new RelSaltador();
        }
        return unicoRelSaltador;
    }
    /**
     * Creates new form RelCarga
     */
    private RelSaltador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco de Atletas - Saltador");
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblSal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "SOBRENOME", "IDADE", "RG", "NOME DA RUA", "NUM CASA", "ID ATLETA", "TEL RESPONSAVEL", "ALTURA SALTO", "CATEGORIA"
            }
        ));
        tblSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1347, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalMouseClicked
        selecTabSal();
    }//GEN-LAST:event_tblSalMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       listaTab();
    }//GEN-LAST:event_formPropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
        listaTab();
    }//GEN-LAST:event_formWindowActivated
    
    public void selecTabSal(){
        String valLinTab = "";
        int posLin = tblSal.getSelectedRow();
        
        for(int coluna = 0;coluna < tblSal.getColumnCount(); coluna++){
            valLinTab += tblSal.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna+1 <tblSal.getRowCount()){
                valLinTab +=" - ";
            }
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
     public void listaTab() {
        DefaultTableModel modelo = (DefaultTableModel) tblSal.getModel();
        int posLin = 0;

        modelo.setRowCount(posLin);

        for (Saltador sal : banco.getBdSal()) {
            modelo.insertRow(posLin, new Object[]{sal.getNome(), sal.getSobrenome(), sal.CalculoIdade(), sal.getRg(), sal.getD1().getRua(), sal.getD1().getNumcasa(), sal.getD1().getIdatleta(), sal.getD1().getTelresponsavel(),sal.getAltura(),sal.getCategoria()});                         
            posLin++;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSal;
    // End of variables declaration//GEN-END:variables
}
